name = input('Hi there what is your name?\n')
print('greetings ' + name)
how = input('How are you today? I am...\n')
print("You are " + how)
print('Oh, well thank you for telling me about it\n')
print('I am glad we are friends, you can talk to me anytime ' + name)
hug = input('can I give u a hug?\n')
print('okay we will do it your way, hugs are a big ' + hug)    
print("now let's get personal")
friends = int(input("how many friends do you have?\n"))    
vegetarians = int(input("how many of them are vegetarians?\n"))    
nonveg = (friends - vegetarians)
print('this number of your frens are not vegetarian')
print(nonveg)
print('okay let us go deeper into your psyche')
temp = int(input('what is the temperature today, give me a number\n'))
temptwo = (temp - 32) // 1.8
print(temptwo)     
print('that is the temp in celcius, captain ' + name)